// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: rpc/v1/worker.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NfsPath       string                 `protobuf:"bytes,1,opt,name=nfs_path,json=nfsPath,proto3" json:"nfs_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapRequest) Reset() {
	*x = MapRequest{}
	mi := &file_rpc_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRequest) ProtoMessage() {}

func (x *MapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRequest.ProtoReflect.Descriptor instead.
func (*MapRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *MapRequest) GetNfsPath() string {
	if x != nil {
		return x.NfsPath
	}
	return ""
}

type MapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	LocalPaths    []string               `protobuf:"bytes,3,rep,name=local_paths,json=localPaths,proto3" json:"local_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapResponse) Reset() {
	*x = MapResponse{}
	mi := &file_rpc_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapResponse) ProtoMessage() {}

func (x *MapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapResponse.ProtoReflect.Descriptor instead.
func (*MapResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *MapResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MapResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MapResponse) GetLocalPaths() []string {
	if x != nil {
		return x.LocalPaths
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_rpc_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_rpc_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_v1_worker_proto protoreflect.FileDescriptor

const file_rpc_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x13rpc/v1/worker.proto\x12\x06rpc.v1\"'\n" +
	"\n" +
	"MapRequest\x12\x19\n" +
	"\bnfs_path\x18\x01 \x01(\tR\anfsPath\"V\n" +
	"\vMapResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vlocal_paths\x18\x03 \x03(\tR\n" +
	"localPaths\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2v\n" +
	"\rWorkerService\x123\n" +
	"\x04Ping\x12\x13.rpc.v1.PingRequest\x1a\x14.rpc.v1.PingResponse\"\x00\x120\n" +
	"\x03Map\x12\x12.rpc.v1.MapRequest\x1a\x13.rpc.v1.MapResponse\"\x00B@Z>github.com/nlduy0310/simple-distributed-mapreduce/rpc/v1;rpcv1b\x06proto3"

var (
	file_rpc_v1_worker_proto_rawDescOnce sync.Once
	file_rpc_v1_worker_proto_rawDescData []byte
)

func file_rpc_v1_worker_proto_rawDescGZIP() []byte {
	file_rpc_v1_worker_proto_rawDescOnce.Do(func() {
		file_rpc_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_worker_proto_rawDesc), len(file_rpc_v1_worker_proto_rawDesc)))
	})
	return file_rpc_v1_worker_proto_rawDescData
}

var file_rpc_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_v1_worker_proto_goTypes = []any{
	(*MapRequest)(nil),   // 0: rpc.v1.MapRequest
	(*MapResponse)(nil),  // 1: rpc.v1.MapResponse
	(*PingRequest)(nil),  // 2: rpc.v1.PingRequest
	(*PingResponse)(nil), // 3: rpc.v1.PingResponse
}
var file_rpc_v1_worker_proto_depIdxs = []int32{
	2, // 0: rpc.v1.WorkerService.Ping:input_type -> rpc.v1.PingRequest
	0, // 1: rpc.v1.WorkerService.Map:input_type -> rpc.v1.MapRequest
	3, // 2: rpc.v1.WorkerService.Ping:output_type -> rpc.v1.PingResponse
	1, // 3: rpc.v1.WorkerService.Map:output_type -> rpc.v1.MapResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_v1_worker_proto_init() }
func file_rpc_v1_worker_proto_init() {
	if File_rpc_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_worker_proto_rawDesc), len(file_rpc_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_worker_proto_goTypes,
		DependencyIndexes: file_rpc_v1_worker_proto_depIdxs,
		MessageInfos:      file_rpc_v1_worker_proto_msgTypes,
	}.Build()
	File_rpc_v1_worker_proto = out.File
	file_rpc_v1_worker_proto_goTypes = nil
	file_rpc_v1_worker_proto_depIdxs = nil
}
