services:
  master:
    container_name: master
    build:
      context: .
      dockerfile: build/master/Dockerfile
    environment:
      - SERVER_PORT=${MASTER_PORT}
      - SERVER_ADVERTISE_ADDR=${MASTER_HOST}:${MASTER_PORT}
      - SVC_HEALTHY_DURATION=10s
      - NFS_ROOT=${NFS_ROOT}
      - INPUT_PATTERN=**/*.txt
    volumes:
      - ${HOST_IN_DIR}:${NFS_ROOT}:z

  worker-1:
    container_name: worker-1
    build:
      context: .
      dockerfile: build/worker/Dockerfile
    command:
      - "--name"
      - "worker-1"
      - "--port"
      - "5000"
      - "--advertise-address"
      - "worker-1:5000"
      - "--master-address"
      - "${MASTER_HOST}:${MASTER_PORT}"
      - "--heartbeat-interval"
      - "5s"
      - "--heartbeat-timeout"
      - "3s"
      - "--nfs-root"
      - "${NFS_ROOT}"
    volumes:
      - ${HOST_IN_DIR}:${NFS_ROOT}:z
    depends_on:
      - master

  worker-2:
    container_name: worker-2
    build:
      context: .
      dockerfile: build/worker/Dockerfile
    command:
      - "--name"
      - "worker-2"
      - "--port"
      - "5000"
      - "--advertise-address"
      - "worker-2:5000"
      - "--master-address"
      - "${MASTER_HOST}:${MASTER_PORT}"
      - "--heartbeat-interval"
      - "2s"
      - "--heartbeat-timeout"
      - "1s"
      - "--nfs-root"
      - "${NFS_ROOT}"
    volumes:
      - ${HOST_IN_DIR}:${NFS_ROOT}:z
    depends_on:
      - master
